import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "white" },
    topBar: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 15,
    },
    appName: { fontSize: 20, fontWeight: "bold", color: "#09c2f0" },
  
    card: {
      backgroundColor: "white",
      margin: 20,
      padding: 20,
      borderRadius: 12,
      elevation: 8,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 5,
    },
    welcomeTitle: {
      fontSize: 22,
      fontWeight: "bold",
      color: "#09c2f0",
      textAlign: "center",
    },
    welcomeDescription: {
      fontSize: 16,
      color: "black",
      textAlign: "center",
      marginTop: 8,
    },
  
    formCard: {
      backgroundColor: "white",
      margin: 20,
      padding: 20,
      borderRadius: 12,
      elevation: 8,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 5,
    },
    formTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#09c2f0",
      marginBottom: 10,
    },
    dropdownContainer: { marginBottom: 15 },
    label: { fontSize: 16, fontWeight: "bold", marginBottom: 5 },
    picker: { height: 50, backgroundColor: "#f9f9f9", borderRadius: 8 },
  
    generateButton: {
      backgroundColor: "#09c2f0",
      padding: 12,
      borderRadius: 8,
      alignItems: "center",
    },
    generateText: { color: "white", fontSize: 16, fontWeight: "bold" },
    // modalContainer: {
    //   flex: 1,
    //   justifyContent: "center",
    //   alignItems: "center",
    //   backgroundColor: "rgba(0,0,0,0.5)",
    // },
    // modalContent: {
    //   width: "85%",
    //   padding: 20,
    //   backgroundColor: "white",
    //   borderRadius: 16,
    //   alignItems: "center",
    // },
    // modalTitle: {
    //   fontSize: 20,
    //   fontWeight: "bold",
    //   color: "#09c2f0",
    //   marginBottom: 20,
    // },
    // inputContainer: {
    //   flexDirection: "row",
    //   alignItems: "center",
    //   borderWidth: 1,
    //   borderColor: "#ddd",
    //   borderRadius: 8,
    //   backgroundColor: "#f9f9f9",
    //   width: "100%",
    //   paddingHorizontal: 10,
    // },
    // input: {
    //   flex: 1,
    //   paddingVertical: 12,
    //   fontSize: 16,
    //   color: "black",
    // },
    // buttonRow: {
    //   flexDirection: "row",
    //   justifyContent: "space-between",
    //   width: "100%",
    //   marginTop: 10,
    // },
    // detectButton: {
    //   flex: 1,
    //   backgroundColor: "#09c2f0",
    //   paddingVertical: 12,
    //   borderRadius: 8,
    //   alignItems: "center",
    //   marginRight: 5,
    // },
    // buttonText: {
    //   color: "white",
    //   fontSize: 14,
    // },
    // cancelButton: {
    //   flex: 1,
    //   backgroundColor: "#ccc",
    //   paddingVertical: 12,
    //   borderRadius: 8,
    //   alignItems: "center",
    //   marginLeft: 5,
    // },
    // cancelText: {
    //   color: "#333",
    //   fontSize: 14,
    // },
    modalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0,0,0,0.5)",
    },
    modalContent: {
      backgroundColor: "#fff",
      padding: 20,
      borderRadius: 10,
      width: "90%",
    },
    modalTitle: {
      fontSize: 20,
      textAlign: "center",
      marginBottom: 20,
    },
    inputContainer: {
      flexDirection: "row",
      alignItems: "center",
      padding: 10,
      backgroundColor: "#f2f2f2",
      borderRadius: 5,
      marginBottom: 10,
    },
    icon: {
      marginRight: 10,
    },
    input: {
      flex: 1,
      fontSize: 16,
    },
    detectTextContainer: {
      padding: 10,
      marginBottom: 10,
    },
    detectText: {
      fontSize: 16,
      color: "#09c2f0",
      textAlign: "center",
    },
    buttonRowModal: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    saveButton: {
      backgroundColor: "#09c2f0",
      padding: 10,
      borderRadius: 5,
      width: "45%",
    },
    saveText: {
      color: "#fff",
      fontSize: 16,
      textAlign: "center",
    },
    cancelButtonModal: {
      backgroundColor: "#ccc",
      padding: 10,
      borderRadius: 5,
      width: "45%",
    },
    cancelTextModal: {
      color: "#000",
      fontSize: 16,
      textAlign: "center",
    },
    menuBar: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      flexDirection: "row",
      justifyContent: "space-around",
      padding: 15,
      backgroundColor: "white",
    },
    menuItem: { alignItems: "center" },
    menuText: { fontSize: 12, color: "gray" },
    activeText: { color: "#09c2f0", fontWeight: "bold" },
  });

export default styles;
